name: Publish Documentation to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 28.2

      - name: Install Org packages
        run: |
          emacs --batch --eval "(require 'package)" \
                         --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
                         --eval "(package-initialize)" \
                         --eval "(package-refresh-contents)" \
                         --eval "(package-install 'org)" \
                         --eval "(package-install 'ox-html)"

      - name: Create static directories
        run: |
          mkdir -p docs/static/css
          
          # Create style.css if it doesn't exist
          if [ ! -f docs/static/css/style.css ]; then
            cat > docs/static/css/style.css << 'EOF'
/* Count Fig Documentation Stylesheet */
body {
    font-family: 'Open Sans', sans-serif;
    margin: 0;
    padding: 0;
    color: #333;
    background-color: #f8f8f8;
    line-height: 1.6;
}
#content {
    max-width: 900px;
    margin: 0 auto;
    padding: 20px;
    background-color: white;
    box-shadow: 0 0 10px rgba(0,0,0,0.1);
}
.title {
    color: #2c3e50;
    font-size: 2.5em;
    text-align: center;
    margin-bottom: 0.5em;
    border-bottom: 1px solid #eee;
    padding-bottom: 0.5em;
}
h1, h2, h3, h4, h5, h6 {
    color: #2c3e50;
    margin-top: 1.5em;
    margin-bottom: 0.5em;
}
a {
    color: #3498db;
    text-decoration: none;
}
a:hover {
    text-decoration: underline;
}
code {
    background-color: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 3px;
    padding: 0 5px;
    font-family: 'Courier New', monospace;
}
pre {
    background-color: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 3px;
    padding: 10px;
    overflow-x: auto;
}
pre code {
    border: none;
    background-color: transparent;
    padding: 0;
}
table {
    border-collapse: collapse;
    width: 100%;
    margin: 20px 0;
}
table, th, td {
    border: 1px solid #ddd;
}
th, td {
    padding: 8px;
    text-align: left;
}
th {
    background-color: #f0f0f0;
}
img {
    max-width: 100%;
    height: auto;
}
EOF
          fi

      - name: Build site
        run: |
          cat > publish.el << 'EOF'
(require 'package)
(package-initialize)
(require 'ox-publish)

(setq org-publish-project-alist
      '(("count-fig-org"
         :base-directory "./docs/"
         :base-extension "org"
         :publishing-directory "./docs/html/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :auto-preamble t
         :section-numbers nil
         :author "Jaynams Ahh"
         :email ""
         :auto-sitemap t
         :sitemap-filename "sitemap.org"
         :sitemap-title "Site Map"
         :sitemap-sort-files anti-chronologically
         :sitemap-file-entry-format "%t"
         :html-doctype "html5"
         :html-html5-fancy t
         :html-head-include-default-style nil
         :html-head "<link rel=\"stylesheet\" href=\"static/css/style.css\" type=\"text/css\"/>")
        
        ("count-fig-static"
         :base-directory "./docs/static/"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf"
         :publishing-directory "./docs/html/static/"
         :recursive t
         :publishing-function org-publish-attachment)
        
        ("count-fig-docs" :components ("count-fig-org" "count-fig-static"))))

(org-publish-all t)
EOF
          mkdir -p docs/html
          emacs --batch --load publish.el

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/html
          clean: true
